# Generated by Django 5.0.6 on 2026-09-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explication pédagogique affichée après réponse')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Option de réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est la bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du Quiz / Examen')),
                ('quiz_type', models.CharField(choices=[('MODULE_QUIZ', 'Quiz de fin de module'), ('FINAL_EXAM', 'Examen final de certification')], default='MODULE_QUIZ', max_length=20, verbose_name="Type d'évaluation")),
                ('description', models.TextField(blank=True, default='', verbose_name='Instructions / Description')),
                ('pass_percentage', models.PositiveIntegerField(default=75, verbose_name='Score minimum requis (%)')),
                ('time_limit_minutes', models.PositiveIntegerField(default=15, verbose_name='Temps limite (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.certification', verbose_name='Certification liée')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.module', verbose_name='Module lié')),
            ],
            options={
                'verbose_name': 'Quiz / Examen',
                'verbose_name_plural': 'Quiz & Examens',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Score obtenu')),
                ('total_points', models.FloatField(default=0.0, verbose_name='Points totaux')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Pourcentage obtenu (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('answers_data', models.JSONField(blank=True, default=dict, verbose_name='Détail des réponses')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de passage')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentative de Quiz',
                'verbose_name_plural': 'Tentatives de Quiz',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Secondes regardées')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='Dernier visionnage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progresses', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='courses.video')),
            ],
            options={
                'verbose_name': 'Progression Vidéo',
                'verbose_name_plural': 'Progressions Vidéos',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
