# Generated by Django 5.0.6 on 2026-09-02 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Description courte')),
                ('level', models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé')], default='BEGINNER', max_length=20, verbose_name='Niveau')),
                ('estimated_hours', models.PositiveIntegerField(default=20, verbose_name='Durée estimée (heures)')),
                ('price', models.DecimalField(decimal_places=0, default=25000, max_digits=10, verbose_name='Prix complet (FCFA)')),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500, verbose_name='Image de couverture (URL ou chemin)')),
                ('prerequisites', models.TextField(blank=True, default='Aucun prérequis spécifique. Connaissances de base en informatique recommandées.', verbose_name='Prérequis')),
                ('learning_outcomes', models.TextField(blank=True, default='', verbose_name='Objectifs pédagogiques')),
                ('badge_name', models.CharField(blank=True, default='Cyber Defender', max_length=100, verbose_name='Nom du badge')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du module')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, default=10000, max_digits=10, verbose_name='Prix individuel du module (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.certification', verbose_name='Certification')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du chapitre')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('video_url', models.CharField(max_length=500, verbose_name='URL de la vidéo (MP4, YouTube, Stream)')),
                ('duration_seconds', models.PositiveIntegerField(default=420, verbose_name='Durée en secondes')),
                ('is_free_override', models.BooleanField(default=False, verbose_name="Forcer l'accès gratuit")),
                ('resources_notes', models.TextField(blank=True, verbose_name='Notes de cours / Téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.chapter', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
