# Generated by Django 5.0.6 on 2026-09-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('CERTIFICATION', 'Certification Complète'), ('MODULE', 'Module Individuel')], default='CERTIFICATION', max_length=20, verbose_name='Type de cible')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='ID de transaction Orange Money')),
                ('sender_phone', models.CharField(max_length=30, verbose_name="Numéro de l'expéditeur")),
                ('sender_name', models.CharField(blank=True, default='', max_length=100, verbose_name="Nom complet de l'expéditeur")),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="Capture d'écran du paiement")),
                ('proof_image_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL de la capture')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de vérification'), ('APPROVED', 'Validé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name="Commentaires de l'administrateur / Motif de refus")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de revue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to='courses.certification', verbose_name='Certification ciblée')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to='courses.module', verbose_name='Module ciblé')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Preuve de paiement',
                'verbose_name_plural': 'Preuves de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('FULL_CERTIFICATION', 'Accès Certification Complète'), ('SINGLE_MODULE', 'Accès Module Individuel')], default='FULL_CERTIFICATION', max_length=30, verbose_name="Type d'accès")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Accordé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.certification', verbose_name='Certification')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.module', verbose_name='Module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('payment_proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_enrollments', to='payments.paymentproof', verbose_name='Preuve de paiement liée')),
            ],
            options={
                'verbose_name': 'Inscription & Accès',
                'verbose_name_plural': 'Inscriptions & Accès',
                'ordering': ['-granted_at'],
            },
        ),
    ]
