# Generated by Django 5.0.6 on 2026-09-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action effectuée')),
                ('target_model', models.CharField(blank=True, default='', max_length=100, verbose_name='Modèle ciblé')),
                ('target_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID de la cible')),
                ('details', models.TextField(blank=True, default='', verbose_name="Détails de l'action")),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur / Admin')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message / Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.lessoncomment', verbose_name='Réponse à')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.video', verbose_name='Vidéo')),
            ],
            options={
                'verbose_name': 'Commentaire de cours',
                'verbose_name_plural': 'Commentaires de cours',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la notification')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('PAYMENT_APPROVED', 'Paiement Validé'), ('PAYMENT_REJECTED', 'Paiement Refusé'), ('CERTIFICATE_ISSUED', 'Certificat Délivré'), ('QUIZ_PASSED', 'Quiz Réussi'), ('COURSE_ACCESS', 'Accès Cours'), ('INFO', 'Information')], default='INFO', max_length=30, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('link_url', models.CharField(blank=True, default='', max_length=255, verbose_name="Lien d'action")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
