# Generated by Django 5.0.6 on 2026-09-02 15:55

import certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(db_index=True, default=certificates.models.generate_certificate_code, max_length=64, unique=True, verbose_name='Numéro unique de certificat')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name="Date d'obtention")),
                ('final_score', models.FloatField(default=100.0, verbose_name='Score final obtenu (%)')),
                ('qr_code_data_uri', models.TextField(blank=True, default='', verbose_name='Code QR (Data URI)')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Certificat révoqué')),
                ('revocation_reason', models.TextField(blank=True, default='', verbose_name='Motif de révocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='courses.certification', verbose_name='Certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Certificat Numérique',
                'verbose_name_plural': 'Certificats Numériques',
                'ordering': ['-issue_date'],
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
